"""add_legal_integrity_fields_to_documents

Revision ID: ab7e7df9f1d8
Revises: 8f481503bd39
Create Date: 2026-01-08 13:06:49.753478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7e7df9f1d8'
down_revision = '8f481503bd39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sha256_hash', sa.String(length=64), nullable=False, comment='Hash SHA256 del archivo original para integridad y deduplicación'))
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='Tamaño en bytes del archivo original'))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=127), nullable=False, comment='Tipo MIME del archivo (ej: application/pdf)'))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Momento exacto de subida al sistema (cadena de custodia)'))
        batch_op.add_column(sa.Column('processing_trace_id', sa.String(length=64), nullable=True, comment='ID del ExecutionTrace que procesó este documento'))
        batch_op.add_column(sa.Column('legal_hold', sa.Boolean(), server_default='false', nullable=False, comment='Si está en litigio activo (no se puede borrar)'))
        batch_op.add_column(sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True, comment='Fecha hasta la que debe conservarse (Art. 30 Código de Comercio: 6 años)'))
        batch_op.create_index(batch_op.f('ix_documents_sha256_hash'), ['sha256_hash'], unique=False)
        batch_op.create_unique_constraint('uq_case_sha256', ['case_id', 'sha256_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_case_sha256', type_='unique')
        batch_op.drop_index(batch_op.f('ix_documents_sha256_hash'))
        batch_op.drop_column('retention_until')
        batch_op.drop_column('legal_hold')
        batch_op.drop_column('processing_trace_id')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('sha256_hash')

    # ### end Alembic commands ###

