"""add_content_type_to_chunks

Revision ID: ef83ab6c54d1
Revises: de73ba5c43f9
Create Date: 2026-01-12 14:30:00.000000

Mejora de chunking: Añade detección de tipo de contenido (table/text/list)
para estrategias adaptativas y metadata enriquecida.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef83ab6c54d1'
down_revision = 'de73ba5c43f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'content_type',
            sa.String(length=50),
            nullable=True,
            comment='Tipo de contenido: table/text/list (opcional)'
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_column('content_type')
    # ### end Alembic commands ###
