"""add_balance_situacion_and_creditos_tables

Revision ID: 251dfe446bba
Revises: c4f5d6e7f8g9
Create Date: 2026-01-09 15:54:27.185696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251dfe446bba'
down_revision = 'c4f5d6e7f8g9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_metadata', sa.JSON(), nullable=True, comment='Metadata de OCR: applied, pages, language, chars_detected (trazabilidad para auditoría)'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256_hash'))
        batch_op.create_index(batch_op.f('ix_documents_sha256_hash'), ['sha256_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256_hash'))
        batch_op.create_index(batch_op.f('ix_documents_sha256_hash'), ['sha256_hash'], unique=1)
        batch_op.drop_column('ocr_metadata')

    # ### end Alembic commands ###

