"""Add legal_report, execution_trace, and hard_manifest tables

Revision ID: de73ba5c43f9
Revises: 168f38a5ec4e
Create Date: 2026-01-10 19:41:33.355189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de73ba5c43f9'
down_revision = '168f38a5ec4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_traces',
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('trace_json', sa.Text(), nullable=False, comment='Serialización JSON del ExecutionTrace'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_traces_case_id'), ['case_id'], unique=False)

    op.create_table('hard_manifests',
    sa.Column('manifest_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('trace_hash', sa.String(length=64), nullable=False, comment='Hash SHA-256 del trace completo'),
    sa.Column('report_hash', sa.String(length=64), nullable=False, comment='Hash SHA-256 del report completo'),
    sa.Column('manifest_json', sa.Text(), nullable=False, comment='Serialización JSON del HardManifest'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['execution_traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manifest_id')
    )
    with op.batch_alter_table('hard_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hard_manifests_trace_id'), ['trace_id'], unique=True)

    op.create_table('legal_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False, comment='Serialización JSON del LegalOutput'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['execution_traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('legal_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_reports_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_reports_trace_id'), ['trace_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_reports_trace_id'))
        batch_op.drop_index(batch_op.f('ix_legal_reports_case_id'))

    op.drop_table('legal_reports')
    with op.batch_alter_table('hard_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hard_manifests_trace_id'))

    op.drop_table('hard_manifests')
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_traces_case_id'))

    op.drop_table('execution_traces')
    # ### end Alembic commands ###

