"""Add audit_logs table for legal compliance

Revision ID: 46c40c4f6a67
Revises: 251dfe446bba
Create Date: 2026-01-10 13:28:47.927567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '46c40c4f6a67'
down_revision = '251dfe446bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create audit_logs table for legal compliance
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('case_id', sa.String(), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for audit_logs
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'])
    op.create_index('ix_audit_logs_case_id', 'audit_logs', ['case_id'])
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'])
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'])
    
    # Drop old tables (cleanup)
    with op.batch_alter_table('creditos_concursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creditos_concursales_balance_id'))
        batch_op.drop_index(batch_op.f('ix_creditos_concursales_creditor_id'))
        batch_op.drop_index(batch_op.f('ix_creditos_concursales_nature'))
        batch_op.drop_index(batch_op.f('ix_creditos_concursales_trlc_classification'))

    op.drop_table('creditos_concursales')
    with op.batch_alter_table('balance_situacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_situacion_case_id'))

    op.drop_table('balance_situacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop audit_logs table
    op.drop_index('ix_audit_logs_timestamp', 'audit_logs')
    op.drop_index('ix_audit_logs_action', 'audit_logs')
    op.drop_index('ix_audit_logs_case_id', 'audit_logs')
    op.drop_index('ix_audit_logs_user_id', 'audit_logs')
    op.drop_table('audit_logs')
    
    # Recreate old tables
    op.create_table('balance_situacion',
    sa.Column('balance_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('fecha_analisis', sa.DATETIME(), server_default=sa.text("'now()'"), nullable=False),
    sa.Column('fecha_cierre', sa.DATETIME(), nullable=True),
    sa.Column('ejercicio', sa.VARCHAR(length=10), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('ruleset_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('superseded_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('balance_data', sqlite.JSON(), nullable=False),
    sa.Column('pyg_data', sqlite.JSON(), nullable=True),
    sa.Column('total_activo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('total_pasivo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('patrimonio_neto', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ratios', sqlite.JSON(), nullable=False),
    sa.Column('insolvencia_actual', sa.BOOLEAN(), nullable=False),
    sa.Column('insolvencia_inminente', sa.BOOLEAN(), nullable=False),
    sa.Column('indicadores_insolvencia', sqlite.JSON(), nullable=False),
    sa.Column('dictamen', sqlite.JSON(), nullable=False),
    sa.Column('confidence', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("'now()'"), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.CheckConstraint('version >= 1', name='ck_balance_version_positive'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name='fk_balance_case_id'),
    sa.ForeignKeyConstraint(['superseded_by'], ['balance_situacion.balance_id'], name='fk_balance_superseded_by'),
    sa.PrimaryKeyConstraint('balance_id'),
    sa.UniqueConstraint('case_id', 'version', name='uq_balance_case_version')
    )
    with op.batch_alter_table('balance_situacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_situacion_case_id'), ['case_id'], unique=False)

    op.create_table('creditos_concursales',
    sa.Column('credit_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('balance_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('creditor_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('creditor_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('principal_amount', sa.VARCHAR(length=20), nullable=False),
    sa.Column('interest_amount', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_amount', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nature', sa.VARCHAR(length=30), nullable=False),
    sa.Column('secured', sa.BOOLEAN(), nullable=False),
    sa.Column('guarantee_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('guarantee_value', sa.VARCHAR(length=20), nullable=True),
    sa.Column('devengo_date', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('source_document_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('source_description', sa.TEXT(), nullable=True),
    sa.Column('trlc_classification', sa.VARCHAR(length=30), nullable=False),
    sa.Column('classification_reasoning', sa.TEXT(), nullable=False),
    sa.Column('excluded_from_categories', sqlite.JSON(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('extraction_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("'now()'"), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balance_situacion.balance_id'], name=op.f('fk_credit_balance_id')),
    sa.PrimaryKeyConstraint('credit_id')
    )
    with op.batch_alter_table('creditos_concursales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creditos_concursales_trlc_classification'), ['trlc_classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditos_concursales_nature'), ['nature'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditos_concursales_creditor_id'), ['creditor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditos_concursales_balance_id'), ['balance_id'], unique=False)

    # ### end Alembic commands ###

